import { defineStore } from "pinia";
export const useProductStore = defineStore("productStore", {
  state: () => ({
    menuHeader: {
      text1: "Don’t miss amazing grocery deals",
      text2: "Sign up for the daily newsletter ",
      input: "Your emaill address",
      button: "Subscribe",
    },
    header: [{}],
    promotion: [
      {
        text: "Everyday Fresh & Clean with Our Products",
        img: new URL("@/assets/img/Onion.png", import.meta.url).href,
        txtBtn: "Shop now",
        btnColor: "#3BB77E",
        bg: "#F3E8E8",
      },
      {
        text: "Make your Breakfast Healthy and Easy",
        img: new URL("@/assets/img/thise.png", import.meta.url).href,
        txtBtn: "Shop now",
        btnColor: "#3BB77E",
        bg: "#F3E8E8",
      },
      {
        text: "The best Organic Products Online",
        img: new URL("@/assets/img/vegetable.png", import.meta.url).href,
        txtBtn: "Shop now",
        btnColor: "#FDC040",
        bg: "#E7EAF3",
      },
    ],

    category: [
      {
        id: "1",
        bg: "#F2FCE4",
        img: new URL("@/assets/img/cat.png", import.meta.url).href,
        title: "Cake & Milk",
        item: "14 items",
      },
      {
        id: "2",
        bg: "#FFFCEB",
        img: new URL("@/assets/img/peach.png", import.meta.url).href,
        title: "Peach",
        item: "17 items",
      },
      {
        id: "3",
        bg: "#ECFFEC",
        img: new URL("@/assets/img/red.png", import.meta.url).href,
        title: "Oganic Kiwi",
        item: "21 items",
      },
      {
        id: "4",
        bg: "#FEEFEA",
        img: new URL("@/assets/img/red_1.png", import.meta.url).href,
        title: "Red Apple",
        item: "68 items",
      },
      {
        id: "5",
        bg: "#FFF3EB",
        img: new URL("@/assets/img/snock.png", import.meta.url).href,
        title: "Snack",
        item: "34 items",
      },
      {
        id: "6",
        bg: "#FFF3FF",
        img: new URL("@/assets/img/black.png", import.meta.url).href,
        title: "Black plum ",
        item: "25 items",
      },
      {
        id: "7",
        bg: "#F2FCE4",
        img: new URL("@/assets/img/veget.png", import.meta.url).href,
        title: "Vegetables",
        item: "65 items",
      },
      {
        id: "8",
        bg: "#FFFCEB",
        img: new URL("@/assets/img/hatphone.png", import.meta.url).href,
        title: "Headphone",
        item: "33 items",
      },
      {
        id: "9",
        bg: "#FFF3FF",
        img: new URL("@/assets/img/milk.png", import.meta.url).href,
        title: "Cake & Milk",
        item: "63 items",
      },
      {
        id: "10",
        bg: "#FFF3FF",
        img: new URL("@/assets/img/orange.png", import.meta.url).href,
        title: "Orange",
        item: "63 items",
      },
    ],

    categoryProduct: [
      {
        categoryProduct:2,
        id: 1,
        tagStyle: "tag-1",
        Tag: "-17%",
        img: new URL("@/assets/img/photo_1.png", import.meta.url).href,
        Name: "Hodo Foods",
        Description: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
        Sky: new URL("@/assets/img/star.png", import.meta.url).href,
        Sky_1: new URL("@/assets/img/star_1.png", import.meta.url).href,
        Sky_Title: "(4.0)",
        Rate: "500gram",
        SellPrice: "$2.51",
        DiscountPercentage: "$5.80",
        IconAdd: "1",
        Up: new URL("@/assets/img/up.png", import.meta.url).href,
        Down: new URL("@/assets/img/down.png", import.meta.url).href,
        currentState: 1,
      },
      {
        categoryProduct:5,
        id: 2,
        tagStyle: "tag-1",
        Tag: "Hot",
        img: new URL("@/assets/img/photo_2.png", import.meta.url).href,
        Name: "Hodo Foods",
        Description: "All Natural Italian-Style Chicken Meatballs",
        Sky: new URL("@/assets/img/star.png", import.meta.url).href,
        Sky_1: new URL("@/assets/img/star_1.png", import.meta.url).href,
        Sky_Title: "(4.0)",
        Rate: "500gram",
        SellPrice: "$2.51",
        DiscountPercentage: "$5.80",
        IconAdd: "Add",
        Plus: new URL("@/assets/img/plus.png", import.meta.url).href,
        currentState: 2,
      },
      {
        categoryProduct:1,
        id: 3,
        tagStyle: "tag-2",
        Tag: "Sale",
        img: new URL("@/assets/img/photo_3.png", import.meta.url).href,
        Name: "Hodo Foods",
        Description: "Angie’s Boomchickapop Sweet & Salty Kettle Corn",
        Sky: new URL("@/assets/img/star.png", import.meta.url).href,
        Sky_1: new URL("@/assets/img/star_1.png", import.meta.url).href,
        Sky_Title: "(4.0)",
        Rate: "500gram",
        SellPrice: "$2.51",
        DiscountPercentage: "$5.80",
        IconAdd: "Add",
        Plus: new URL("@/assets/img/plus.png", import.meta.url).href,
        currentState: 2,
      },
      {
        categoryProduct:1,
        id: 4,
        tagStyle: "tag-3",
        Tag: "n",
        img: new URL("@/assets/img/photo_5.png", import.meta.url).href,
        Name: "Hodo Foods",
        Description: "Foster Farms Takeout Crispy Classic Buffalo Wings",
        Sky: new URL("@/assets/img/star.png", import.meta.url).href,
        Sky_1: new URL("@/assets/img/star_1.png", import.meta.url).href,
        Sky_Title: "(4.0)",
        Rate: "500gram",
        SellPrice: "$2.51",
        DiscountPercentage: "$5.80",
        IconAdd: "Add",
        Plus: new URL("@/assets/img/plus.png", import.meta.url).href,
        currentState: 2,
      },
      {
        categoryProduct:3,
        id: 5,
        tagStyle: "tag-3",
        Tag: "-17%",
        img: new URL("@/assets/img/photo_4.png", import.meta.url).href,
        Name: "Hodo Foods",
        Description: "Blue Diamond Almonds Lightly Salted Vegetables",
        Sky: new URL("@/assets/img/star.png", import.meta.url).href,
        Sky_1: new URL("@/assets/img/star_1.png", import.meta.url).href,
        Sky_Title: "(4.0)",
        Rate: "500gram",
        SellPrice: "$2.51",
        DiscountPercentage: "$5.80",
        IconAdd: "Add",
        Plus: new URL("@/assets/img/plus.png", import.meta.url).href,
        currentState: 2,
      },
      {
        categoryProduct:4,
        id: 6,
        tagStyle: "tag-3",
        Tag: "-17%",
        img: new URL("@/assets/img/photo_6.png", import.meta.url).href,
        Name: "Hodo Foods",
        Description: "Chobani Complete Vanilla Greek Yogurt",
        Sky: new URL("@/assets/img/star.png", import.meta.url).href,
        Sky_1: new URL("@/assets/img/star_1.png", import.meta.url).href,
        Sky_Title: "(4.0)",
        Rate: "500gram",
        SellPrice: "$2.51",
        DiscountPercentage: "$5.80",
        IconAdd: "Add",
        Plus: new URL("@/assets/img/plus.png", import.meta.url).href,
        currentState: 2,
      },
      {
        categoryProduct:8,
        id: 7,
        tagStyle: "tag-1",
        Tag: "Hot",
        img: new URL("@/assets/img/photo_7.png", import.meta.url).href,
        Name: "Hodo Foods",
        Description: "Canada Dry Ginger Ale – 2 L Bottle - 200ml - 400g",
        Sky: new URL("@/assets/img/star.png", import.meta.url).href,
        Sky_1: new URL("@/assets/img/star_1.png", import.meta.url).href,
        Sky_Title: "(4.0)",
        Rate: "500gram",
        SellPrice: "$2.51",
        DiscountPercentage: "$5.80",
        IconAdd: "Add",
        Plus: new URL("@/assets/img/plus.png", import.meta.url).href,
        currentState: 2,
      },
      {
        categoryProduct:6,
        id: 8,
        tagStyle: "tag-3",
        Tag: "-17%",
        img: new URL("@/assets/img/photo_8.png", import.meta.url).href,
        Name: "Hodo Foods",
        Description: "Encore Seafoods Stuffed Alaskan Salmon",
        Sky: new URL("@/assets/img/star.png", import.meta.url).href,
        Sky_1: new URL("@/assets/img/star_1.png", import.meta.url).href,
        Sky_Title: "(4.0)",
        Rate: "500gram",
        SellPrice: "$2.51",
        DiscountPercentage: "$5.80",
        IconAdd: "Add",
        Plus: new URL("@/assets/img/plus.png", import.meta.url).href,
        currentState: 2,
      },
      {
        categoryProduct:10,
        id: 9,
        tagStyle: "tag-3",
        Tag: "-17%",
        img: new URL("@/assets/img/photo_9.png", import.meta.url).href,
        Name: "Hodo Foods",
        Description: "Gorton’s Beer Battered Fish Fillets with soft paper",
        Sky: new URL("@/assets/img/star.png", import.meta.url).href,
        Sky_1: new URL("@/assets/img/star_1.png", import.meta.url).href,
        Sky_Title: "(4.0)",
        Rate: "500gram",
        SellPrice: "$2.51",
        DiscountPercentage: "$5.80",
        IconAdd: "Add",
        Plus: new URL("@/assets/img/plus.png", import.meta.url).href,
        currentState: 2,
      },
      {
        categoryProduct:9,
        id: 10,
        tagStyle: "tag-2",
        Tag: "Sale",
        img: new URL("@/assets/img/photo_10.png", import.meta.url).href,
        Name: "Hodo Foods",
        Description: "Haagen-Dazs Caramel Cone Ice Cream Ketchup",
        Sky: new URL("@/assets/img/star.png", import.meta.url).href,
        Sky_1: new URL("@/assets/img/star_1.png", import.meta.url).href,
        Sky_Title: "(4.0)",
        Rate: "500gram",
        SellPrice: "$2.51",
        DiscountPercentage: "$5.80",
        IconAdd: "Add",
        Plus: new URL("@/assets/img/plus.png", import.meta.url).href,
        currentState: 2,
      },
    ],
  }),
  actions: {
    getCat(cat) {
      return this.$state.category[cat];
    },
    getProd(prod) {
      return this.$state.categoryProduct[prod];
    },
  },
});
